# Generated by Django 3.2.3 on 2021-08-03 15:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100, verbose_name='Judul')),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komen', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255, verbose_name='Judul')),
                ('status', models.CharField(choices=[('trending', 'Trending'), ('biasa', 'Biasa')], default='draft', max_length=10, verbose_name='Status')),
                ('waktu_publish', models.DateTimeField(verbose_name='Created')),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d')),
                ('konten', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('author', models.CharField(default='Anonymous', max_length=60, verbose_name='Created by')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.kategori', verbose_name='Kategori')),
                ('komens', models.ManyToManyField(to='portal.Komentar')),
            ],
        ),
    ]
