# Generated by Django 3.2.3 on 2021-08-07 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='komens',
        ),
        migrations.AddField(
            model_name='posting',
            name='komens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.komentar'),
        ),
    ]
