# Generated by Django 3.2.3 on 2021-08-07 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210808_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='komens',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.komentar'),
        ),
    ]
